/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    examples: Example;
    users: User;
    tests: Test;
    media: Media;
    forms: Form;
    'form-submissions': FormSubmission;
    'pdf-templates': PdfTemplate;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    'pdf-header': PdfHeader;
    'pdf-footer': PdfFooter;
    'pdf-watermarks': PdfWatermark;
    'pdf-fonts': PdfFont;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examples".
 */
export interface Example {
  id: string;
  someField?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tests".
 */
export interface Test {
  id: string;
  someField?: string | null;
  sampleArray?:
    | {
        sampleText?: string | null;
        sampleTextArea?: string | null;
        sampleRichText?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  sampleGroup?: {
    sampleDate?: string | null;
    sampleEmail?: string | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    samplePoints?: [number, number] | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?:
              | {
                  [k: string]: unknown;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf-templates".
 */
export interface PdfTemplate {
  id: string;
  title?: string | null;
  assignedCollections?: ('examples' | 'tests') | null;
  pageOptions: {
    orientation?: ('portrait' | 'landscape') | null;
    pageSize?:
      | (
          | 'letter'
          | 'government-letter'
          | 'legal'
          | 'junior-legal'
          | 'ledger'
          | 'tabloid'
          | 'credit-card'
          | 'a0'
          | 'a1'
          | 'a2'
          | 'a3'
          | 'a4'
          | 'a5'
          | 'a7'
          | 'a8'
          | 'a9'
          | 'a10'
          | 'b0'
          | 'b1'
          | 'b2'
          | 'b3'
          | 'b4'
          | 'b5'
          | 'b6'
          | 'b7'
          | 'b8'
          | 'b9'
          | 'b10'
          | 'c0'
          | 'c1'
          | 'c2'
          | 'c3'
          | 'c4'
          | 'c5'
          | 'c6'
          | 'c7'
          | 'c8'
          | 'c9'
          | 'c10'
          | 'd1'
          | 'custom'
        )
      | null;
    customPageSize?: {
      length: number;
      width: number;
    };
    margins: {
      topMargin: number;
      bottomMargin: number;
      leftMargin: number;
      rightMargin: number;
    };
  };
  layoutOptions?: {
    useHeader?: boolean | null;
    useFooter?: boolean | null;
    useWatermark?: boolean | null;
  };
  fontOptions: {
    defaultFontSize?: number | null;
    fonts?: ('test' | 'test2')[] | null;
    defaultTextColor: string;
  };
  pathOptions: {
    defaultFillColor: string;
    defaultStrokeColor: string;
    defaultLineColor: string;
    defaultStrokeWidth?: number | null;
    defaultLineWidth?: number | null;
    defaultLineCapStyle?: string | null;
    defaultLineJoinStyle?: string | null;
  };
  fileOptions?: {
    buttonBehavior?: ('download' | 'newTab' | 'curTab' | 'autoprint') | null;
    fileNameField?: string | null;
  };
  useEncryption?: boolean | null;
  encryptionSettings?: {
    userPassword?: string | null;
    ownerPassword?: string | null;
    userPermissions?: ('print' | 'modify' | 'copy' | 'annot-forms')[] | null;
  };
  defaultDisplayMode?: {
    zoom?: ('fullwidth' | 'fullheight' | 'fullpage' | 'original') | null;
    layout?: ('continuous' | 'single' | 'twoleft' | 'tworight') | null;
    outlineDisplay?: ('none' | 'UseOutlines' | 'UseThumbs') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf-header".
 */
export interface PdfHeader {
  id: string;
  title?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf-footer".
 */
export interface PdfFooter {
  id: string;
  footerLayout?:
    | {
        layoutName: string;
        topDivider?: boolean | null;
        pageNumbers?: boolean | null;
        companyName?: boolean | null;
        contactInfo?: boolean | null;
        backgroundSettings?: {
          layoutBackground?: ('blank' | 'solid' | 'image') | null;
          backgroundImage?: string | Media | null;
          width?: number | null;
          height?: number | null;
          footerFillColor?: string | null;
          horizontalMargin?: number | null;
          verticalMargin?: number | null;
        };
        dividerSettings?: {
          dividerStrokeColor?: string | null;
          dividerThickness?: number | null;
          horizontalMargin?: number | null;
          verticalMargin?: number | null;
        };
        pageNumberSettings?: {
          format?: string | null;
          collate?: boolean | null;
          footerLocation?: ('left' | 'center' | 'right') | null;
        };
        companyNameSettings?: {
          companyName?: string | null;
          footerLocation?: ('left' | 'center' | 'right') | null;
        };
        contactInfoSettings?: {
          phoneNumber?: string | null;
          email?: string | null;
          address?: string | null;
          footerLocation?: ('left' | 'center' | 'right') | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf-watermarks".
 */
export interface PdfWatermark {
  id: string;
  watermarks?:
    | {
        watermark?: string | Media | null;
        width?: number | null;
        height?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf-fonts".
 */
export interface PdfFont {
  id: string;
  fontList?:
    | {
        fontFile?: string | Media | null;
        fontName?: string | null;
        fontWeight?: ('bold' | 'italic' | 'normal' | 'bolditalic') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}